services:
  mysql-test:
    image: mysql:8.0
    container_name: rustexpress-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_rustexpress
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"  # Using different port to avoid conflictsa
    volumes:
      - mysql_test_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 5s
    tmpfs:
      - /tmp
      - /var/run/mysqld

volumes:
  mysql_test_data:
    driver: local
