name: Deploy Express to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'apps/Express/**'
      - '.github/workflows/deploy-express.yml' # Trigger if this workflow file changes

# Hardcoded path, tidak perlu secret
env:
  VPS_TARGET_DIR: /home/azureuser/ultimate-asepharyana.cloud

jobs:
  build-and-deploy-express:
    name: Build and Deploy Express
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 22 and Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Prepare .env file for production
        env:
          ENV_FILE_PRODUCTION: ${{ secrets.ENV_FILE_PRODUCTION }}
        run: |
          if [ -n "$ENV_FILE_PRODUCTION" ]; then
            echo "$ENV_FILE_PRODUCTION" > .env
          fi
      - name: Install Dependencies
        run: bun install

      - name: Build Express
        run: bun run build --filter=Express

      - name: Check Build Output
        run: |
          echo "Express build output:" && ls -l apps/Express/dist
          if [ -z "$(ls -A apps/Express/dist)" ]; then
            echo "ERROR: Express build output is empty. Deployment aborted."
            exit 1
          fi

      - name: SSH into VPS and Prepare Express Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.VPS_TARGET_DIR }}
            mkdir -p apps/Express/dist

      - name: Sync Express Build Artifacts to VPS
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > /tmp/deploy_key && chmod 600 /tmp/deploy_key
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key" apps/Express/dist/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.VPS_TARGET_DIR }}/apps/Express/dist/
          rm -f /tmp/deploy_key

      - name: SSH into VPS and Deploy Express
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH="$HOME/.bun/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
            source ~/.bashrc
            cd ${{ env.VPS_TARGET_DIR }}
            git pull # Need to pull to get the ecosystem.config.cjs
            bun install --filter=Express # Install dependencies only for Express
            pm2 startOrRestart apps/Express/ecosystem.config.cjs
            echo "Express Deployment successful!"