name: Build and Deploy Specific Folders

on:
  push:
    branches:
      - main

# Hardcoded path, tidak perlu secret
env:
  VPS_TARGET_DIR: /root/ultimate-asepharyana.cloud

jobs:
  build-and-deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: true
      - name: Prepare .env file for production
        env:
          ENV_FILE_PRODUCTION: ${{ secrets.ENV_FILE_PRODUCTION }}
        run: |
          if [ -n "$ENV_FILE_PRODUCTION" ]; then
            echo "$ENV_FILE_PRODUCTION" > .env
          fi
      - name: Build with Turborepo
        run: pnpm run build
      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            password: ${{ secrets.VPS_PASSWORD }}
            script: |
                # Masuk ke direktori target
                cd ${{ env.VPS_TARGET_DIR }}
                git pull origin main
                pnpm install
      - name: Debug File Structure
        run: ls -R

      - name: Sync Files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: |
            apps/NextJS/.next
            apps/Express/dist
          target: ${{ env.VPS_TARGET_DIR }}
          strip_components: 0 # Menjaga struktur direktori

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Masuk ke direktori target
            cd ${{ env.VPS_TARGET_DIR }}

            # Setup environment untuk pnpm
            export PATH=$PATH:/root/.local/share/pnpm

            # Install dependencies untuk seluruh workspace
            # pnpm akan secara cerdas menginstal dependensi yang diperlukan untuk
            # Next.js dan Express berdasarkan package.json yang diunggah

            # Reload aplikasi menggunakan PM2
            pm2 restart express
            pm2 restart nextjs
            echo "Deployment successful!"