name: Build and Deploy Specific Folders

on:
  push:
    branches:
      - main

# Hardcoded path, tidak perlu secret
env:
  VPS_TARGET_DIR: /home/azureuser/ultimate-asepharyana.cloud

jobs:
  build-and-deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 22 and Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Prepare .env file for production
        env:
          ENV_FILE_PRODUCTION: ${{ secrets.ENV_FILE_PRODUCTION }}
        run: |
          if [ -n "$ENV_FILE_PRODUCTION" ]; then
            echo "$ENV_FILE_PRODUCTION" > .env
          fi
      - name: Install Dependencies
        run: bun install

      - name: Build with Turborepo
        run: bun run build
      - name: Check Build Output
        run: |
          echo "NextJS build output:" && ls -l apps/NextJS/.next
          echo "Express build output:" && ls -l apps/Express/dist
          if [ -z "$(ls -A apps/NextJS/.next)" ] && [ -z "$(ls -A apps/Express/dist)" ]; then
            echo "ERROR: Build output is empty. Deployment aborted."
            exit 1
          fi
      - name: SSH into VPS and Prepare Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Menggunakan SSH keya
          script: |
            # Masuk ke direktori target
            cd ${{ env.VPS_TARGET_DIR }}
            source ~/.bashrc
            # Pastikan direktori apps/NextJS/.next dan apps/Express/dist ada
            mkdir -p apps/NextJS/.next
            mkdir -p apps/Express/dist
      - name: Sync Build Artifacts to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Menggunakan SSH key
          script: |
            # Masuk ke direktori target
            source ~/.bashrc
            rsync -avz --delete apps/NextJS/.next/ ${{ env.VPS_TARGET_DIR }}/apps/NextJS/.next/
            rsync -avz --delete apps/Express/dist/ ${{ env.VPS_TARGET_DIR }}/apps/Express/dist/

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Menggunakan SSH key
          script: |
            # Masuk ke direktori target
            source ~/.bashrc
            cd ${{ env.VPS_TARGET_DIR }}

            # Install dependencies untuk seluruh workspace
            bun install

            # Start/Restart Express dengan ecosystem.config.js
            pm2 startOrRestart apps/Express/ecosystem.config.js

            # Start/Restart NextJS dengan ecosystem.config.js
            pm2 startOrRestart apps/NextJS/ecosystem.config.js

            echo "Deployment successful!"
